[package]
name = "holochain_serialized_bytes"
version = "0.0.36"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
description = "serialized bytes for holochain"
keywords = ["holochain", "holo", "messagepack", "json", "serialization"]
categories = ["database"]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/holochain_serialized_bytes"
repository = "https://github.com/holochain/holochain-serialization"
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["serde_derive"] }
serde_json = { version = "1.0.48", features = ["preserve_order"] }
holochain_serialized_bytes_derive = { version = "=0.0.36", path = "../holochain_serialized_bytes_derive" }
rmp-serde = "0.14.3"
serde-transcode = "1.1.0"
