[package]
name = "holochain_serialized_bytes"
version = "0.0.24"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
description = "serialized bytes for holochain"
keywords = ["holochain", "holo", "messagepack", "json", "serialization", "serde"]
categories = ["database"]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/holochain_json_api"
repository = "https://github.com/holochain/holochain-serialization"

[dependencies]
serde = "=1.0.104"
serde_derive = "=1.0.104"
serde_json = { version = "=1.0.47", features = ["preserve_order"] }
rmp-serde = "=0.14.3"
serde-transcode = "=1.1.0"
