version: 2

jobs:
 build:
  docker:
   - image: holochain/holochain-rust:circle.01.warm.nix
  steps:
   - checkout
   - run: nix-shell --run hcs-test

workflows:
 version: 2
 tests:
  jobs:
   - build
